# Docker core
alias dk='docker'
alias dkb='docker build'
alias dki='docker images'
alias dkps='docker ps'
alias dkpsa='docker ps -a'
alias dkpl='docker pull'
alias dkph='docker push'
alias dkr='docker run'
alias dkR='docker run -e COLUMNS=`tput cols` -e LINES=`tput lines` -i -t --rm'
alias dkRe='docker run -e COLUMNS=`tput cols` -e LINES=`tput lines` -i -t --rm --entrypoint /bin/bash'
alias dke='docker exec'
alias dkE='docker exec -e COLUMNS=`tput cols` -e LINES=`tput lines` -i -t'
alias dkl='docker logs'
alias dkL='docker logs -f'
alias dkst='docker start'
alias dkx='docker stop'
alias dkrst='docker restart'
alias dkrm='docker rm'
alias dkrmi='docker rmi'
alias dksypr='docker system prune'

# Docker Compose
alias dkc='docker compose'
alias dkcb='docker compose build'
alias dkcB='docker compose build --no-cache'
alias dkcu='docker compose up'
alias dkcU='docker compose up -d'
alias dkcd='docker compose down'
alias dkcps='docker compose ps'
alias dkcl='docker compose logs'
alias dkcL='docker compose logs -f'
alias dkce='docker compose exec -e COLUMNS=`tput cols` -e LINES=`tput lines`'
alias dkcx='docker compose stop'
alias dkcrst='docker compose restart'
alias dkcpl='docker compose pull'
